name: Build & Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tourist-backend ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/tourist-backend ${{ secrets.DOCKER_USERNAME }}/tourist-backend:latest

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tourist-frontend ./frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/tourist-frontend ${{ secrets.DOCKER_USERNAME }}/tourist-frontend:latest

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tourist-backend:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tourist-frontend:latest
